# Generated by Django 4.1.2 on 2022-10-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moto',
            old_name='kilometros',
            new_name='contacto',
        ),
    ]
