# Generated by Django 4.1.2 on 2022-11-02 22:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0003_publicacion_extensionmoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='linea_texto',
            field=ckeditor.fields.RichTextField(max_length=400),
        ),
    ]
