# Generated by Django 4.1.2 on 2022-11-02 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0005_publicacion_fecha_publicacion_publicacion_subtitulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_publicacion',
        ),
    ]
