# Generated by Django 4.1.2 on 2022-11-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0006_remove_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moto',
        ),
    ]
