# Generated by Django 4.1.2 on 2022-11-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0007_delete_moto'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
