# Generated by Django 4.1.2 on 2022-11-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0008_publicacion_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
