# Generated by Django 4.1.2 on 2022-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0010_remove_publicacion_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
