# Generated by Django 4.1.2 on 2022-11-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0014_publicacion_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='avatar',
            new_name='imagen',
        ),
        migrations.DeleteModel(
            name='ExtensionPublicacion',
        ),
    ]
