# Generated by Django 4.1.2 on 2022-11-06 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='autor',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
