# Generated by Django 4.1.2 on 2022-11-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0003_chat_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='autor',
        ),
    ]
