# Generated by Django 4.1.2 on 2022-11-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0004_remove_chat_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
